bikelomatic-complexity/btc-app

package.json
www/js/actions/actions.js
www/js/app.js
www/js/components/main-page.js
www/js/components/my-map.js
www/js/components/point-card.js
www/js/reducers/reducer.js

http://rackt.org/redux/index.html

using redux

---

.gitignore
package.json
test/mock-data.js
test/point-card-tests.js
test/sanity-tests.js
www/js/components/main-page.js
www/js/components/my-map.js
www/js/components/point-card.js

Tests for the new view-info card.

View info tests

---

www/js/app.js
www/js/components/ac-drawer.js
www/js/components/add-point-page.js
www/js/components/device-storage.js
www/js/components/download-track-page.js

Shows a download track page
mock data for downloading, saving, cancel and removing tracks

Download track

---

www/css/flex-objects.css
www/css/index.css
www/js/components/ac-drawer.js
www/js/components/add-point-card.js
www/js/components/device-storage.js
www/js/components/download-track-page.js
www/js/components/login-page.js

form-column now sets the margin and scroll for vertical forms
point-details have no scrolling by default
removed dummy links in the title menu
moved login to the bottom of the title menu
set value prop for textfield (not children)
use camel case instead of hyphen for jsx styles
removed form-column classes
fixed indentation

Polish the UI

---

www/js/app.js
www/js/components/register-page.js

When a user clicks on Login > Sign Up, they are taken to a new page where they can register for an account.

Register page

---

package.json

include cordova plugin geolocation on start of android app install

gps (hot fix)

---

www/js/app.js
www/js/components/ac-drawer.js
www/js/components/setting-switch.js
www/js/components/settings-page.js

Adds sync settings and other settings (which are currently blank)

add settings page to client

---

www/js/components/add-point-page.js
www/js/components/filter-page.js
www/js/components/login-page.js
www/js/components/map-page.js
www/js/components/register-page.js
www/js/components/settings-page.js

remove extra un-needed divs

---

www/js/components/ac-drawer.js
www/js/components/add-point-card.js
www/js/components/add-point-page.js
www/js/components/device-storage.js
www/js/components/drop-down.js
www/js/components/filter-drop-down.js
www/js/components/filter-page.js
www/js/components/hammer-point-card.js
www/js/components/hours-table.js
www/js/components/point-card.js
www/js/components/point-map.js
www/js/reducers/reducer.js

Made lines in components to be close to or less than 80 characters. In this process, some un-used dependencies were removed, and repeated code was saved to variables.

Shorter lines

---

package.json
www/js/components/device-storage.js
www/js/components/download-track-page.js

show cordova free space on download page

---

www/js/components/add-point-card.js

Add point here changes when you click location

set new message for add point

---

www/js/components/download-track-page.js
www/js/components/map-page.js
www/js/mock-data.js

Cleans up a lot of component code.

use mock file instead of hardcoded values in components

---

www/css/index.css

I forgot this in the last PR, sorry Ethan.

add generic font fall back

---

.gitignore
.travis.yml
package.json
scripts/postrelease-android.js

This branch enables Travis to build pull requests on master, and is able to generate release apk packages.

Setup travis to build master and release .apk's

---

config.xml
package.json

Remove cordova plugin and platform commands from package.json, and declare them in config.xml
fixes #44

Clean plugins

---

www/js/components/add-point-card.js
www/js/components/drop-down.js
www/js/components/filter-page.js

bunch'o'fixes.
hot fix: not being able to select a type
hot-fix: not showing correct filters after selecting and removing previous filters

hot fix: sorry

---

www/css/index.css
www/js/components/point-card.js

Makes the view a bit nicer... specifically for the buttons (but mostly a refactor)

View points flex

---

www/js/components/add-point-description.js

The phone keyboard works, and the website keyboard works. Should be future proof if we decide on Material-UI

use special keyboards, yay

---

www/js/components/point-card.js

less paper, more scroll

---

www/js/containers/add-point-page.js
www/js/containers/main.js
www/js/reducers/dialog.js
www/js/reducers/index.js

You can write dialogs that appear on the application!
Information about how to construct one is in the `reducers/dialog.js` file.
when you `setDialog` it will open the dialog with the settings you provide it. 
If you `closeDialog`, it will clear the state for the dialog and close the modal- **this is automatically triggered when any of the action buttons are pressed** so there is no need to call it unless you are waiting for specific conditions (i.e. on an async function).
example for image below is as follows:
```js
setDialog({
title:"testing dialog",
description:"testing dialog description",
modal:true,
actions:[
{label:"cancel"},
{label:"submit", disabled:true}
]
});
```

Dialog with dispatch commands

---

www/js/components/point-map.js

filter on amentities and type

---

www/js/components/add-point-amenities.js
www/js/components/add-point-hours.js
www/js/components/drop-down.js

Use Time Picker for selecting hours
Get and Set Value of dropdown through refs
Put amenities button on top, have amenities listed like filter page

Time Picker

---

.eslintignore
.eslintrc
package.json

fixed lint and added eslintignore

---

src/js/app.js
src/js/components/point-list.js
src/js/containers/drawer.js
src/js/containers/list-page.js
src/js/containers/publish-page.js
test/js/components/point-list.spec.js

It's just view logic, but there's also some refactoring for the list views...

Publish page

---

src/js/components/point-map.js

Zooms after finding the location.

zooms after finding location

---

src/js/containers/wizard/add-alert-page.js
src/js/containers/wizard/add-service-page.js
src/js/containers/wizard/tabs.js
src/js/containers/wizard/update-service-page.js

On windows the app failed to hit add-service paths because of `//` existing in the url. This has been removed.

hotfix - new paths are correct now

---

src/js/containers/filter-page.js

Selection of items below the dropdown, and buttons take up width appropriately.

Page and button styling on filter page
